name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - name: Print Message
        run: echo "Hello GitHub Actions!"